name: cv_skin_disease
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipython=9.1
  - ipykernel=6.29
  - datasets=3.5
  - numpy=2.0.1
  - seaborn=0.13
  - scikit-learn=1.6
  - pip
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.57.0
      - matplotlib==3.10.1
      - pillow==11.0.0
      - polars==1.27.1
      - pyparsing==3.2.3
      - sympy==1.13.1
      - torch==2.6.0
      - torchvision==0.21.0